<a href="https://colab.research.google.com/github/olusipedaniel/zero-to-mastery-exercises/blob/main/00_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🛠 00 TensorFlow Fundamentals Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [3]:
import tensorflow as tf
import numpy as np

# Create a Scalar
A1 = tf.constant(10)

# Create a vector
A2 = tf.constant([5, 10])

# Create a matrix and find the shape, rank and size.
A3 = tf.constant([[1, 4],
                  [7, 10]])

# Create a tensor and find the shape, rank and size.
A4 = tf.constant([[[1, 2],
                  [3, 4]],
                 [[6, 7],
                  [7, 8]],
                 [[8, 9],
                 [9,10]]])

### 2. Find the shape, rank and size of the tensors you created in 1.

In [4]:
# Finding the shape, rank and size
print("The shape of the tensor is:", A4.shape, "\n")
print("The rank of the tensor is:", A4.ndim, "\n") 
print("The size of the tensor is:", tf.size(A4))

The shape of the tensor is: (3, 2, 2) 

The rank of the tensor is: 3 

The size of the tensor is: tf.Tensor(12, shape=(), dtype=int32)


### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [5]:
# Set seed
tf.random.set_seed(1)
# Setting up the shape of the tensor
B1 = tf.random.uniform(shape= [5,300], minval= 0, maxval= 1)
B2 = tf.random.uniform(shape= [5,300], minval= 0, maxval= 1)
B1, B2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.16513085, 0.9014813 , 0.6309742 , ..., 0.01223373, 0.10674465,
         0.7973399 ],
        [0.6007875 , 0.00949216, 0.10104156, ..., 0.8316059 , 0.13676643,
         0.2744167 ],
        [0.10485208, 0.00733125, 0.9611858 , ..., 0.3587792 , 0.41688943,
         0.20882547],
        [0.44241273, 0.7811512 , 0.9335252 , ..., 0.89712286, 0.8038093 ,
         0.5238483 ],
        [0.03471053, 0.224473  , 0.5711684 , ..., 0.6693133 , 0.7461662 ,
         0.06386542]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.51010704, 0.44353175, 0.4085331 , ..., 0.6993296 , 0.3549732 ,
         0.15760994],
        [0.04775882, 0.17832983, 0.8899392 , ..., 0.6746143 , 0.40816212,
         0.80723894],
        [0.63969266, 0.67977285, 0.19325793, ..., 0.51353157, 0.42205584,
         0.3196032 ],
        [0.40856254, 0.8768741 , 0.59874177, ..., 0.4151665 , 0.55399   ,
         0.92848015],
        [0.71899

### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [6]:
# The two tensors created can't be matrix multiplied because the inner dimension are not the same so there is need to transpose one of the tensors
B1_transpose = tf.transpose(B1)
B2_transpose = tf.transpose(B2)
B1_transpose, B2_transpose

(<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
 array([[0.16513085, 0.6007875 , 0.10485208, 0.44241273, 0.03471053],
        [0.9014813 , 0.00949216, 0.00733125, 0.7811512 , 0.224473  ],
        [0.6309742 , 0.10104156, 0.9611858 , 0.9335252 , 0.5711684 ],
        ...,
        [0.01223373, 0.8316059 , 0.3587792 , 0.89712286, 0.6693133 ],
        [0.10674465, 0.13676643, 0.41688943, 0.8038093 , 0.7461662 ],
        [0.7973399 , 0.2744167 , 0.20882547, 0.5238483 , 0.06386542]],
       dtype=float32)>, <tf.Tensor: shape=(300, 5), dtype=float32, numpy=
 array([[0.51010704, 0.04775882, 0.63969266, 0.40856254, 0.71899056],
        [0.44353175, 0.17832983, 0.67977285, 0.8768741 , 0.45436585],
        [0.4085331 , 0.8899392 , 0.19325793, 0.59874177, 0.7723112 ],
        ...,
        [0.6993296 , 0.6746143 , 0.51353157, 0.4151665 , 0.7167101 ],
        [0.3549732 , 0.40816212, 0.42205584, 0.55399   , 0.5629829 ],
        [0.15760994, 0.80723894, 0.3196032 , 0.92848015, 0.5602329 ]],
       

In [7]:
# Matrix multiplying tensors B1 and B2_transpose
tf.matmul(B1, B2_transpose)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.866776, 72.238686, 73.00015 , 74.3029  , 74.33906 ],
       [72.69711 , 70.90695 , 73.91422 , 72.84128 , 74.97523 ],
       [77.04567 , 78.9836  , 77.01749 , 80.76424 , 80.3436  ],
       [78.79129 , 79.310524, 81.438934, 77.94879 , 80.564896],
       [75.12534 , 76.56512 , 75.78966 , 77.09797 , 78.97676 ]],
      dtype=float32)>

In [8]:
# Or Matrix multiplying tensors B1_transpose and B2
tf.matmul(B1_transpose, B2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.38571024, 0.65536624, 0.91408753, ..., 0.7831779 , 0.6127228 ,
        0.97473377],
       [0.9455381 , 1.193476  , 1.01922   , ..., 1.1257908 , 0.8860946 ,
        1.0031284 ],
       [1.7336216 , 2.0293672 , 1.5335119 , ..., 1.7999529 , 1.509616  ,
        1.6749575 ],
       ...,
       [1.1232262 , 1.4883915 , 1.8684766 , ..., 1.6059719 , 1.3690066 ,
        1.9958318 ],
       [1.192557  , 1.3989962 , 1.3034364 , ..., 1.2494997 , 1.1350461 ,
        1.4248142 ],
       [0.81336206, 1.0329034 , 0.9732849 , ..., 1.1132246 , 0.8093386 ,
        0.9360921 ]], dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

In [9]:
# Multiplying tensors B1 and B2_transpose using dot product
tf.tensordot(B1, B2_transpose, axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.866776, 72.238686, 73.00015 , 74.3029  , 74.33906 ],
       [72.69711 , 70.90695 , 73.91422 , 72.84128 , 74.97523 ],
       [77.04567 , 78.9836  , 77.01749 , 80.76424 , 80.3436  ],
       [78.79129 , 79.310524, 81.438934, 77.94879 , 80.564896],
       [75.12534 , 76.56512 , 75.78966 , 77.09797 , 78.97676 ]],
      dtype=float32)>

In [10]:
# Multiplying tensors B1_transpose and B2 using dot product
tf.tensordot(B1, B2_transpose, axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.866776, 72.238686, 73.00015 , 74.3029  , 74.33906 ],
       [72.69711 , 70.90695 , 73.91422 , 72.84128 , 74.97523 ],
       [77.04567 , 78.9836  , 77.01749 , 80.76424 , 80.3436  ],
       [78.79129 , 79.310524, 81.438934, 77.94879 , 80.564896],
       [75.12534 , 76.56512 , 75.78966 , 77.09797 , 78.97676 ]],
      dtype=float32)>

### Further pratice on dot product

In [11]:
# Creating a rank 3 tensor
B3 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

B4 = tf.constant([[[7, 8, 9], [1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [1, 2, 3], [4, 5, 6]]])
B3, B4

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[7, 8, 9],
         [1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 2, 3],
         [4, 5, 6]]], dtype=int32)>)

In [12]:
# Multiplying the rank 3 tensors created earlier using dot product
tf.tensordot(B3, B4, axes = 3)

<tf.Tensor: shape=(), dtype=int32, numpy=408>

### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [13]:
# Set seed
tf.random.set_seed(2)
# Setting the shape of the tensor
C1 = tf.random.uniform(shape=[224, 224, 3], minval= 0, maxval= 1)
C1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.14690244, 0.46425676, 0.22489977],
        [0.35288846, 0.9857408 , 0.99910235],
        [0.5648881 , 0.16375077, 0.9890269 ],
        ...,
        [0.03802752, 0.14310706, 0.84929407],
        [0.85379016, 0.13300359, 0.83217883],
        [0.05494165, 0.8953632 , 0.21623874]],

       [[0.8642839 , 0.89559436, 0.47133732],
        [0.6835743 , 0.6609303 , 0.2674172 ],
        [0.21034217, 0.8745489 , 0.9309293 ],
        ...,
        [0.24778223, 0.59047747, 0.3125658 ],
        [0.796983  , 0.8057469 , 0.9332074 ],
        [0.73379886, 0.5882416 , 0.41613305]],

       [[0.9621011 , 0.7402241 , 0.14632273],
        [0.04302502, 0.10561955, 0.80846226],
        [0.27705956, 0.36593628, 0.7974299 ],
        ...,
        [0.22384119, 0.39379752, 0.17685866],
        [0.36734855, 0.868816  , 0.5893227 ],
        [0.6404797 , 0.32257414, 0.5572417 ]],

       ...,

       [[0.5918008 , 0.4555453 , 0.0715667 ],
        [0.74

### 7. Find the min and max values of the tensor you created in 6.

In [14]:
# Finding minimum and maximum values of the tensor
print(f"The Minimum value is: {tf.reduce_min(C1)}")
print(f"The Maximum value is: {tf.reduce_max(C1)}")

The Minimum value is: 8.344650268554688e-07
The Maximum value is: 0.9999978542327881


### 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [15]:
# Set seed
tf.random.set_seed(3)
# Creating a tensor with random values of shape [1, 224, 224, 3]
D1 = tf.random.uniform(shape=([1, 224, 224, 3]))
D1

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.13366318, 0.5678531 , 0.4963317 ],
         [0.01686525, 0.50454175, 0.74873126],
         [0.13033688, 0.33561492, 0.6519277 ],
         ...,
         [0.09551287, 0.7745788 , 0.94565904],
         [0.4585389 , 0.24478483, 0.69737494],
         [0.13486624, 0.49011993, 0.3190508 ]],

        [[0.9132737 , 0.7370925 , 0.82477975],
         [0.7902572 , 0.8107809 , 0.61262596],
         [0.54857635, 0.7577503 , 0.6478059 ],
         ...,
         [0.22832298, 0.42732084, 0.3243487 ],
         [0.1258465 , 0.9693099 , 0.72472024],
         [0.17262292, 0.5402758 , 0.01245522]],

        [[0.18029809, 0.6981578 , 0.36399138],
         [0.16166258, 0.56943595, 0.22409868],
         [0.37093806, 0.2099936 , 0.91768014],
         ...,
         [0.04689181, 0.8925816 , 0.5845498 ],
         [0.19480121, 0.04620397, 0.83770967],
         [0.12744379, 0.22989404, 0.27232206]],

        ...,

        [[0.6833439 , 0.15678465, 

In [16]:
# Squeezing it to change the shape to [224, 224, 3].
D1 = tf.squeeze(D1)
D1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.13366318, 0.5678531 , 0.4963317 ],
        [0.01686525, 0.50454175, 0.74873126],
        [0.13033688, 0.33561492, 0.6519277 ],
        ...,
        [0.09551287, 0.7745788 , 0.94565904],
        [0.4585389 , 0.24478483, 0.69737494],
        [0.13486624, 0.49011993, 0.3190508 ]],

       [[0.9132737 , 0.7370925 , 0.82477975],
        [0.7902572 , 0.8107809 , 0.61262596],
        [0.54857635, 0.7577503 , 0.6478059 ],
        ...,
        [0.22832298, 0.42732084, 0.3243487 ],
        [0.1258465 , 0.9693099 , 0.72472024],
        [0.17262292, 0.5402758 , 0.01245522]],

       [[0.18029809, 0.6981578 , 0.36399138],
        [0.16166258, 0.56943595, 0.22409868],
        [0.37093806, 0.2099936 , 0.91768014],
        ...,
        [0.04689181, 0.8925816 , 0.5845498 ],
        [0.19480121, 0.04620397, 0.83770967],
        [0.12744379, 0.22989404, 0.27232206]],

       ...,

       [[0.6833439 , 0.15678465, 0.74756753],
        [0.59

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [17]:
# Creating a tensor with shape [10]
E1 = tf.constant(np.random.randint(1, 10, 10))
E1

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([6, 2, 2, 3, 1, 4, 4, 6, 8, 3])>

In [18]:
# Finding the index with the maximum value 
print(f'The indices where the value is maximum: {tf.argmax(E1)}')
print(f'The maximum value is: {E1[tf.argmax(E1)]}')

The indices where the value is maximum: 8
The maximum value is: 8


### 10. One-hot encode the tensor you created in 9.

In [19]:
# One-hot encoding the tensor
tf.one_hot(E1, depth= 10, on_value= "YES", off_value= "NO")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'YES', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'YES', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'YES', b'NO', b'NO',
        b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'NO', b'YES',
        b'NO'],
       [b'NO', b'NO', b'NO', b'YES', b'NO', b'NO', b'NO', b'NO', b'NO',
        b'NO']], dtype=object)>